# Generated by Django 3.0.6 on 2020-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=10)),
                ('startup', models.CharField(max_length=100)),
            ],
        ),
    ]
